### ISSUE TITLE
Where is the location data?

### ISSUE THREAD

**Issue by pauldeng** [u-blox/ubxlib_cellular_applications_xplr_iot#10]
Hi repo owner,

Appreciate your hard work.

I notice that the location is not included in the MQTT payload. Seems location has a seperate json format defined in locationTask.c.

```json
{
  "Timestamp": "05:09:54.643",
  "CellQuality": {
    "RSRP": "-97",
    "RSRQ": "-12",
    "RSSI": "-63",
    "SNR": "0"
  },
  "CellInfo": {
    "RxQual": "3",
    "CellID": "192",
    "EARFCN": "9410",
    "PLMN": "50501",
    "Operator": "Telstra Mobile"
  }
}
```

I would recommend adding location data into SignalQuality payload like this:
```json
{
  "Timestamp": 1692091468,
  "Location": {
    "Altitude": 123.456,
    "Latitude": 234.567,
    "Longitude": 345.678,
    "Accuracy": 1.2,
    "Speed": 23.4,
    "UnixTimeStamp": 1692091468
  },
  "CellQuality": {
    "RSRP": "-97",
    "RSRQ": "-12",
    "RSSI": "-63",
    "SNR": "0"
  },
  "CellInfo": {
    "RxQual": "3",
    "CellID": "192",
    "EARFCN": "9410",
    "PLMN": "50501",
    "Operator": "Telstra Mobile"
  }
}
```

Cheers,
Paul

**Comment by philwareublox** [comment]
The LocationTask and SignalQualityTask are completely separate. Each 'appTask' publishes to it's own Topic. It's just the design we have.

**Comment by philwareublox** [comment]
The location will be output in the <imei>/Location topic you'll have to subscribe to, and the location will only be output once a GNSS fix has been made. You should see the WHITE LED flash when this happens.
