### ISSUE TITLE
How to interpret CellID?

### ISSUE THREAD

**Issue by pauldeng** [u-blox/ubxlib_cellular_applications_xplr_iot#11]
Hi repo owner,

Appreciate your hard work.

In the SignalQuality MQTT payload, it reports CellID like this:
```json
{
  "Timestamp": "05:09:54.643",
  "CellQuality": {
    "RSRP": "-97",
    "RSRQ": "-12",
    "RSSI": "-63",
    "SNR": "0"
  },
  "CellInfo": {
    "RxQual": "3",
    "CellID": "192",
    "EARFCN": "9410",
    "PLMN": "50501",
    "Operator": "Telstra Mobile"
  }
}
```

Can I ask how to map this CellID to a map?
Do you know any service that allow me to easily check the location of this cellular tower?

Cheers,
Paul

**Comment by philwareublox** [comment]
This will be changing in the next days.... We will be publishing both Physical Cell ID and Logical Cell ID. 
Please see the AT Manual for the SARA_R5 module, +UCGED. 

There is an opensource cell mapping web site: https://www.cellmapper.net
You should be able to use that to see the cell locations from the EARCFN and CellID  (especially when I add both IDs)

**Comment by pauldeng** [comment]
Can I ask how do you read it?

If I click cell tower icon in the cellmapper, I should be able to match the `Cell Identifier` with `Physical Cell ID` which you are going to add soon? What is the `Logical Cell ID` used for?
![image](https://github.com/u-blox/ubxlib_cellular_applications_xplr_iot/assets/341848/f926ad45-8f57-4942-a7b3-c7d4d6ade6ea)

**Comment by philwareublox** [comment]
The "Cell Identified" in the cellmapper.net web app is the Logical Cell ID - as reported by the +CEREG AT command/URC
The **PCI** is the Physical Cell ID, as reported in the +UCGED AT command command

[15:22:05.734] +UCGED: 2
[15:22:05.734] 6,4,234,10
[15:22:05.734] 6400,20,50,50,1b0,7ba7082,**115**,d737b924,fffc,88,50,8,-5.62,1,255,255,255,255,255,0,255,255,0,0
[15:22:05.734] OK
[15:22:16.394] 
[15:22:16.394] +CEREG: 5,"01b0","07ba7078",7

![image](https://github.com/u-blox/ubxlib_cellular_applications_xplr_iot/assets/20516919/ca0146da-1669-4e4c-8f32-478cbe4edc96)

**Comment by philwareublox** [comment]
Physical and logical Cell ID is now reported in the CellInfo JSON
Fixed in: https://github.com/u-blox/ubxlib_cellular_applications_xplr_iot/tree/v1.0-DriveTestFixes
