### ISSUE TITLE
Wrong comport search on Linux

### ISSUE THREAD

**Issue by pauldeng** [u-blox/ubxlib_cellular_applications_xplr_iot#13]
Hi repo owner,

Appreciate your hard work.

My XPLR-IOT-1 is PCBA Revision C, and I am trying this repo on Ubuntu 20.04 in VirtualBox. 

In the do file, it looks for UART0 with name `CP210.+Interface 0` which is wrong for my board. It should look for `/dev/ttyUSB0` in my case.

Cheers,
Paul

**Comment by philwareublox** [comment]
I will have to look into this... (I'm on windows, but will ask our linux expert.)

**Comment by philwareublox** [comment]
Hi. 
The naming of the correct COM Port maybe different on different machines and it will not always be the very first COM Port. 
With Rev B the enumerated COM Ports where named and we could search for the "CP210x..... Interface 0" name.

You will need to select the com port manually with the --uart-name argument.
