### ISSUE TITLE
MQTT failed to reconnect

### ISSUE THREAD

**Issue by pauldeng** [u-blox/ubxlib_cellular_applications_xplr_iot#19]
Hi repo owner,

I put the device into Faraday Cage for a while. 

When I take the device out, it seems reconnected to LTE-M, but failed to reconnect to MQTT. 

Here is the log look like: (note that the `errValue` is empty)
```text
{"Timestamp":1692853227,"CellQuality":{"RSRP":-99,"RSRQ":-12,"RSSI":-67,"SNR":0},"CellInfo":{"RxQual":3,"CellID":"192","EARFCN":"9410","PLMN":"50501","Operator":"Telstra Mobile"}}

*** WARNING ************************************************
05:00:31.318: Failed to publish MQTT message,  error:

{"Timestamp":1692853257,"CellQuality":{"RSRP":-98,"RSRQ":-14,"RSSI":-61,"SNR":1},"CellInfo":{"RxQual":1,"CellID":"192","EARFCN":"9410","PLMN":"50501","Operator":"Telstra Mobile"}}

*** WARNING ************************************************
05:01:01.398: Failed to publish MQTT message,  error:

{"Timestamp":1692853287,"CellQuality":{"RSRP":-100,"RSRQ":-13,"RSSI":-65,"SNR":-2},"CellInfo":{"RxQual":2,"CellID":"192","EARFCN":"9410","PLMN":"50501","Operator":"Telstra Mobile"}}

*** WARNING ************************************************
05:01:31.479: Failed to publish MQTT message,  error:
```

Can I ask what is the best way to reconnect MQTT?

Cheers,
Paul

**Comment by philwareublox** [comment]
The MQTT appTask should look after the connection, so I believe this issue is due to an older version of firmware in the SARA-R5 module.  Please see here how to update the firmware in the SARA-R5 module: https://github.com/u-blox/ubxlib_cellular_applications_xplr_iot#note-1-xplr-iot-1-sara-r5-firmware-version

**Comment by pauldeng** [comment]
I am trying to restore SensorAggration firmware by the BAT file in Windows, but shows
![image](https://github.com/u-blox/ubxlib_cellular_applications_xplr_iot/assets/341848/12aa0e8f-a269-4f76-a809-f7915dece9ec)
Can I ask what should I do?

Thanks,

**Comment by pauldeng** [comment]
It was my bad. I had TeraTerm open and it was auto connect to my COM port.

Now, I have reverted back to the SensorAggreation firmware.

Following the Section 5.3 in User Guide, but stuck on step 7. Update with EasyFlash:
![image](https://github.com/u-blox/ubxlib_cellular_applications_xplr_iot/assets/341848/93e3561c-a583-43c1-a20d-58a690dcab3e)

**Comment by rebatoma** [comment]
Thanks @pauldeng, then I belive we can close this issue.

**Comment by philwareublox** [comment]
You will need to send the sara_r5 power_on command from the terminal to allow the update to start.

**Comment by pauldeng** [comment]
sara r5 powered on, but still could not easy flash it:
```
[0] Task alfConfigureUart:\\.\COM28:0:115200 finished with status 0
[1] alfUartSetBaudrate:115200
[1] Task alfUartSetBaudrate:115200 finished with status 0
[2] alfUartConnectToBootrom
[2] Connecting to bootrom (reset it now)...
[2] Connection timeout. Trying again..
[2] Connecting to bootrom (reset it now)...
[2] Connection timeout. Trying again..
[2] Connecting to bootrom (reset it now)...
[2] Connection timeout. Trying again..
[2] Connecting to bootrom (reset it now)...
[2] Connection timeout. Trying again..
[2] Connecting to bootrom (reset it now)...
[2] Connecting to bootrom failed, exiting...
[2] Task alfUartConnectToBootrom finished with status 1
ERROR: task failed
Error occured!

STOPPING...
[Boot target failed.]
```
Need your help.

**Comment by philwareublox** [comment]
I don't know what COM port your SARA-R5 module is on, and you might have to have a manual look at the terminal for each. 

You should be able to send the modules SARAR5 power_on command and then send "AT" to the terminal on the other com port(s) to see what port the SARA-R5 module is on. You can then close that terminal and use that COM Port for EasyFlash

Looking at the User Guide, Rev C devices should have the SARA-R5 module @ the next enumerated COM PORT from the command terminal first com port.

**Comment by pauldeng** [comment]
Ok, I figured out.

The [User Guide](https://content.u-blox.com/sites/default/files/documents/XPLR-IOT-1_UserGuide_UBX-21035674.pdf) needs to be updated, the correct steps should be below:

Notice that you should click SART in EasyFlash then power_on the module.

```text
...
4. Start EasyFlash firmware update utility. Select the product (SARA-R5), port (COM port associated with port B), and baud rate (3,000,000 or slower) from the drop-down menus.
5. Open a terminal program, such as Putty [32] or TeraTerm [33], to the virtual COM port (VCP) for NORA-B1 (port A) with the settings 115,200 bps, no parity, 8 data bits, 1 stop bit. Set terminal
line endings to carriage return only (CR, or hex 0x0d).
6. Start the update with EasyFlash.
7. NORA-B1 terminal: Type the following command to enable SARA-R5 over the USB-UART port B:
      modules SARAR5 power_on
8. When the update is complete, close EasyFlash.
9. NORA-B1 terminal: Power-cycle SARA-R5 to activate the new firmware.
      modules SARAR5 power_off
      modules SARAR5 power_on
10. Start m-center. Connect to SARA-R5 and start an AT command terminal from m-center on the VCP associated with port B.
11. m-center terminal: reset NVM to factory defaults
      AT+UFACTORY=0,2
...
```

I do not think the steps after 11 is necessary for SARA R5 firmware upgrade. Please comment.

Some other useful tips:
- Run EasyFlash in Administrator mode
- Make sure EasyFlash is in writeable folder

Cheers,
Paul

**Comment by philwareublox** [comment]
Correct, points 6 and 7 need to be swapped in the user guide update. 

You **_MUST_** perform step 27, the AT+USIO=2 command as well, after the update.

**Comment by philwareublox** [comment]
I believe those other points about EasyFlash are mentioned in the EasyFlash documentation.
