### ISSUE TITLE
Do not use leading forward slash in MQTT topic

### ISSUE THREAD

**Issue by pauldeng** [u-blox/ubxlib_cellular_applications_xplr_iot#8]
Hi repo owner,

Appreciate your hard work.

I notice that the MQTT topic has leading forward slash which is not the best practice:

- https://community.home-assistant.io/t/status-change-and-mqtt-publication/335090/22#never-use-a-leading-forward-slash
- https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/
- https://docs.aws.amazon.com/whitepapers/latest/designing-mqtt-topics-aws-iot-core/mqtt-design-best-practices.html
- https://github.com/dotnet/MQTTnet/wiki/MQTT-topics

Would you please consider removing it?

Cheers,
Paul

**Comment by philwareublox** [comment]
Thanks for the tip - I will change this.

**Comment by pauldeng** [comment]
I try to fix this but confused, seems timestamp is a bit off. No idea where is the problem.

This is what I did, I added few lines to debug in registrationTask.c.
```c
        // remove the current local tick time from this
        // to obtain a rough "boot" time value.
        printf("time %" PRId64 "\n", time);
        printf("seconds %d \n", (uPortGetTickTimeMs() / 1000));
        unixNetworkTime = time - (uPortGetTickTimeMs() / 1000);
        printf("unixNetworkTime %" PRIu32 "\n", unixNetworkTime);
```

Then use TeraTerm to log local timestamp, here it is:
```log
[2023-08-17 16:16:58.870] 20243: Buttons #1 and #2 are now enabled
[2023-08-17 16:17:56.037] 77419: Connected to Cellular Network: Telstra Mobile (50501)
[2023-08-17 16:17:56.119] time 1692253123 // 16:18:43, not close to my wall clock
[2023-08-17 16:17:56.119] seconds 77 
[2023-08-17 16:17:56.119] unixNetworkTime 1692253046 //16:17:26, not close to my wall clock
```

None of `time` and `unixNetworkTime` are close to my wall clock.

Cheers,
Paul

**Comment by philwareublox** [comment]
The application uses the uPortGetTickTimeMs() function to return the tick time since the module booted. 
If the network isn't restricted, then it will request the time from the NTP server. It will then remove the current tick time so that the logging time is correct as this already uses the tick time. 
If you can, print out the time reported by the NTP Server too.

Can you detail why you are wanting to change this?

**Comment by pauldeng** [comment]
I realise I posted to the wrong issue.

Let me re-post it and answer it there...

Sorry.

**Comment by philwareublox** [comment]
Fixed in https://github.com/u-blox/ubxlib_cellular_applications_xplr_iot/tree/v1.0-DriveTestFixes
